### ISSUE TITLE
The interface of GeCoNet has issues.

### ISSUE THREAD

**Issue by Galaxy-228** [KSUNetSE/GeCoNet-Tool#2]
Dear GeCoNet Development Team,
Thanks so much for developing the GeCoNet software.
When I downloaded GeCoNet on my laptop with a Windows system, something went wrong as described: the Data Processing cannot be operated because the 'Start' button is missing

![image](https://github.com/user-attachments/assets/a0d73af8-4766-4bb7-8d66-7d090337d1fc)

Best wishes,
Jie

**Comment by KSUNetSE** [comment]
Hello Jie,

The author of the code is no longer part of the group. I will see if he can help, or I will find additional support.
Please give me some time.

Best,
Caterina
________________________________
From: Jie Liu ***@***.***>
Sent: Thursday, August 15, 2024 7:47 AM
To: KSUNetSE/GeCoNet-Tool ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [KSUNetSE/GeCoNet-Tool] The interface of GeCoNet has issues. (Issue #2)


This email originated from outside of K-State.


Dear GeCoNet Development Team,
Thanks so much for developing the GeCoNet software.
When I downloaded GeCoNet on my laptop with a Windows system, something went wrong as described: the Data Processing cannot be operated because the 'Start' button is missing

image.png (view on web)<https://github.com/user-attachments/assets/a0d73af8-4766-4bb7-8d66-7d090337d1fc>

Best wishes,
Jie

**Comment by Galaxy-228** [comment]
Thanks so much for your reply.

**Comment by KSUNetSE** [comment]
I think you are not getting the entire window with the start button. 
Can you please try to enlarge the interface window? You can do this by dragging out the lower left corner of the window.

**Comment by Galaxy-228** [comment]
Thanks for your reply, I have tried to enlarge the interface window, but it does not work, the 'start' button still does not appear.
You can try downloading it on a Windows system to see if encounter the same issue


Thanks again.













------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "KSUNetSE/GeCoNet-Tool"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年8月22日(星期四) 凌晨3:23
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [KSUNetSE/GeCoNet-Tool] The interface of GeCoNet has issues. (Issue #2)





 
I think you are not getting the entire window with the start button.
 Can you please try to enlarge the interface window? You can do this by dragging out the lower left corner of the window.

**Comment by KSUNetSE** [comment]
We downloaded it, and it works perfectly. However, when we rescale the window to make it smaller, the start button disappears.

**Comment by Galaxy-228** [comment]
Thanks for your reply.
I installed it on a Windows 11 system. The interface after installation is shown in the attachment. As you can see, the interface is incomplete, and it cannot be normalized by dragging.


Is there a command line version that runs directly on Linux currently?


Thanks again.



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "KSUNetSE/GeCoNet-Tool"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年8月22日(星期四) 晚上9:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [KSUNetSE/GeCoNet-Tool] The interface of GeCoNet has issues. (Issue #2)





 
We downloaded it, and it works perfectly. However, when we rescale the window to make it smaller, the start button disappears.

**Comment by KSUNetSE** [comment]
I cannot see the attachment. Can you try again?

**Comment by Galaxy-228** [comment]
Thank for reply,
<img width="671" alt="11ebd311a4a2c9c65c772fa1700a11a" src="https://github.com/user-attachments/assets/b4974d0e-00c5-4e58-b248-f9506452b8ad">
<img width="872" alt="316bb239958779b56f7cdbf23430ede" src="https://github.com/user-attachments/assets/2605dc26-241e-43b8-ace3-53db449c3dfa">

**Comment by MatinMarjani** [comment]
Hello Jie,
I only experience your problem when I resize the window to a smaller size ( by dragging the edges, Otherwise It shows fine like the pictures I attached.) If dragging is not working for you I'll try and change the user interface to always show the entire window.  
![image](https://github.com/user-attachments/assets/70e3b591-7c9c-49d3-8ff0-283835043503)
![image](https://github.com/user-attachments/assets/d53d2ceb-7799-4a58-bf46-53d7177d9a93)

**Comment by Galaxy-228** [comment]
Thanks,
I've tried many times and indeed can not make it normalized by dragging.
Looking forward to your update.

Thanks again.

**Comment by Galaxy-228** [comment]
Thanks,
I've tried many times and indeed can not make it normalized by dragging. And I've also tried on different computers (all running Windows system), but the same problem persists.
Looking forward to your update.

Thanks again.

**Comment by MatinMarjani** [comment]
Hello Jie,
I forked this rep and changed the window size so you should now be able to use the Maximize button on top right of the app to make it full screen and be able to access all there is in it. Here is the link to it :
https://github.com/MatinMarjani/GeCoNet-Tool/releases/tag/v1.2
Please try it and give me your feeback. 
Thank you.

**Comment by KSUNetSE** [comment]
Hi Jie,

Did you try the new version to solve your problem? Did it work?
Please let me know.

Best,
Caterina
________________________________

**Comment by Galaxy-228** [comment]
Caterina,
Sorry for the late reply. I had seen that the topic was already closed, so I didn't respond.
Now the GeCONet software can run normally. 
But I have one more question: how do I export the images generated by the software?
<img width="1275" alt="4a62fab23bb78579d7af9ad99032c06" src="https://github.com/user-attachments/assets/2d3f5214-aa97-4247-8b58-da1b9dcbb996">

Thanks so much.

**Comment by Galaxy-228** [comment]
Caterina,
Sorry for the late reply. I had seen that the topic was already closed, so I didn't respond.
Now the GeCONet software can run normally.

Thanks so much.
Best,
Jie
